# 启用 vi
# CTL+b+[
setw -g mode-keys vi

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'nordtheme/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
# 会话记录
set -g @plugin 'tmux-plugins/tmux-resurrect'
# # 重启恢复会话
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com/user/plugin'
# set -g @plugin 'git@bitbucket.com/user/plugin'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# paru -S tmux-plugin-manager
run -b '/usr/share/tmux-plugin-manager/tpm'
