server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "fuzzel"

[fuzzel]
menu_length = 75
extra_arguments = ["--config=/home/black/.config/fuzzel/clipcat.ini"]

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
